# .graphclientrc.yml
sources:
  - name: base-sepolia
    handler:
      graphql:
        endpoint: https://api.studio.thegraph.com/query/88691/geomarket/version/latest
documents:
  - "./queries/*.graphql"
plugins:
  - pollingLive:
      defaultInterval: 10000
      pauseOnBackground: true
